import { GameState } from '@/types/game';

export const INITIAL_GAME_STATE: GameState = {
  mode: 'classic_fc',
  score: 0,
  handsPlayed: 0,
  cardsSelected: 0,
  timeElapsed: 0,
  timeRemaining: 60,
  isPlaying: false,
  isPaused: false,
  isGameOver: false,
  isLevelComplete: false,
  isBonusLevel: false,
  isBonusFailed: false,
  isProcessingSelection: false,
  lastHandLengthChangeAt: null,
  selectedCards: [],
  deck: [],
  usedCards: [],
  currentHand: null,
  sscLevel: 1,
  sscPhase: 'sitting_duck',
  sscRound: 1,
  levelGoal: 500,
  earnedPowerUps: [],
  activePowerUps: [],
  powerUpChoices: [],
  showPowerUpSelection: false,
  rawScore: 0,
  timeBonus: 0,
  leftoverPenalty: 0,
  bonusRoundCount: 0,
  pendingBonusRound: false,
  bonusTimePoints: 0,
  levelScore: 0,
  cumulativeScore: 0,
  reshuffleTrigger: 0,
  previousHandRank: null,
  betterHandStreak: 0,
  currentMultiplier: 1,
  starRating: 0,
  hasSeenSSCExplainer: false,
  // Bonus round reward system
  pendingReward: null,
  rewardTier: null,
  showLootBox: false,
  inventoryFull: false,
  // Phase override for Classic/Blitz modes
  phaseOverride: undefined,
};
